# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc94236bcb3c69a3ad116a114b20e10cb5fc815488f22c55ef3a6faa86d55204ee26bd013fa3ed4eeeea00a4b0773e5f113735b156683c56acb83b5e18d744d5

test:
  secret_key_base: 7ccf3abc89532e3213dd9b865eb658bdd37fb16ebff7258c7a9a9246bdb205f2c04551674d0ae144d8cceb91e27347dcb88141833ea6fd5f21a45ceb8f0e0ec7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
